### ISSUE TITLE
update needed I think, stopped working a few days ago

### ISSUE THREAD

**Issue by Simon7381** [natefox/aws-ssh-rdp-links#2]
Hi, really great tool but I think it needs an update as it stopped working a few days ago?

Thanks

**Comment by natefox** [comment]
Will get to that shortly. Was on vacation.

I really need to rewrite a section to make it more dynamic so it isnt
affected by these changes!

**Comment by natefox** [comment]
Fix has been pushed to google. Should update automagically within 24hrs.
