### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by DimitarV** [natefox/aws-ssh-rdp-links#4]
Hi,
I have added Chrome add on (0.1.8). On AWS EC2 page I see small RDP labels next to IPs, but on click nothing happens. Open in new tab, shows link similar to:
rdp://username=s:Administrator&full%20address=s:<IP address>

what else have to be conferred to invite rdp client ?
I'm running on Windows 10.

Regards,
Dimitar

**Comment by natefox** [comment]
I'm not sure whats happening with Windows. According to the url scheme link in the [README](/README.md) the code is generating the right links (I tested this on a new Server 2016 EC2 instance as my desktop is a mac).

That being said, when I click on things it does nothing. If I create a simple html page with a test link (like `rdp://username=s:Administrator&full%20address=s:1.2.3.4:3389`) and click on it in IE, I get "You'll need a new app to open this rdp". In chrome it just doesnt open (like you've mentioned). 

I have no idea why MS decided to break their stuff. I investigated adding it to the registry but it looks fairly involved plus you'd have to somehow parse it as passing the url to the program failed for me: `"%systemroot%\system32\mstsc.exe" "rdp://username=s:Administrator&full%20address=s:1.2.3.4:3389"`

My only guess would be to install a 3rd party program that overrides Microsoft's URL handler and reassigns it as its own, so clicking the link would open said 3rd party program. I have no idea if any of the 'RDP Manager' style programs do this.

I'll leave this open and if I (or anyone else) get a chance to dive into it deeper.

**Comment by DimitarV** [comment]
Hi,
Make it - what I did:
 - get some ideas from here: http://www.jjclements.co.uk/2010/02/21/rdp-hyperlink/
 - add rdp association into registry:
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\rdp]
@="URL:Remote Desktop Connection"
"URL Protocol"=""

[HKEY_CLASSES_ROOT\rdp\DefaultIcon]
@="C:\\WINDOWS\\System32\\mstsc.exe"

[HKEY_CLASSES_ROOT\rdp\shell]

[HKEY_CLASSES_ROOT\rdp\shell\open]

[HKEY_CLASSES_ROOT\rdp\shell\open\command]
@="\"C:\\Windows\\System32\\wscript.exe\" \"C:\\WINDOWS\\hyperlink-rdp.js\" \"%1\""

- create a parser (hyperlink-rdp.js) in c:\windows:
var server=(WScript.Arguments(0))
var prefix='rdp://'
var app='C:\\WINDOWS\\system32\\mstsc.exe'
server=server.replace(prefix, '')
server=server.replace('/', '')
label = "full%20address=s:"
server = server.substring( server.indexOf(label)+label.length, server.length)
var shell = new ActiveXObject("WScript.Shell")
shell.Exec(app + " /v:" + server)

Agree that [https://technet.microsoft.com/en-us/windows-server-docs/compute/remote-desktop-services/clients/remote-desktop-uri](url) is not working.

Regards,
Dimitar

**Comment by Kmalamer** [comment]
> Hi, I have added Chrome add on (0.1.8). On AWS EC2 page I see small RDP labels next to IPs, but on click nothing happens. Open in new tab, shows link similar to: rdp://username=s:Administrator&full%20address=s:
> 
> what else have to be conferred to invite rdp client ? I'm running on Windows 10.
> 
> Regards, Dimitar
